version: 2
jobs:
  build_test_publish:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: set env
          command: |
            COMMITISH=$(cat ~/repo/commitish)
            echo 'export COMMITISH=$COMMITISH' >> $BASH_ENV
      - run:
          name: build
          command: >
            docker build \
             -t hypnosapos/visdom:$COMMITISH \
             -t hypnosapos/visdom:latest .
      - run:
          name: test
          command: |
            docker run -d -p 8097:8097 hypnosapos/visdom:$COMMITISH
            pip install -U pip
            pip install git+https://github.com/facebookresearch/visdom@$COMMITISH#egg=visdom
            ./visdom_connection_test.py
      - run:
          name: build
          command: |
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            docker push hypnosapos/visdom:$COMMITISH
            docker push hypnosapos/visdom:latest
workflows:
  version: 2
  build:
    jobs:
    - build_test_publish:
        filters:
          branches:
            only: master